apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cert-manager-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
